AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'
    - 'spec/rails_helper.rb'

Style/Documentation:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 112
