AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'
    - 'spec/rails_helper.rb'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 112

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
